### ISSUE TITLE
All actions now break which makes it hard to debug remote repositories

### ISSUE THREAD

**Issue by vickytnz** [fofr/govuk-design-history#304]
The new github actions mean that when I copy the template the workflows all break. I though that this might be because I did a private repo without Github pages, but when I tried a repo which was public and had pages it still didn't work.

Examples of actions breaking here:
https://github.com/vickytnz/xgov-design-history/actions

I don't really want this working on Github pages as i'd rather have it on a password protected heroku, but the breaking tests seem to mean I can work locally but not remotely. 

Ideally there would be a way to turn off this workflow until it's set up on github pages (or not at all), and have it as a toggle.

**Comment by frankieroberto** [comment]
@vickytnz ah, thanks for reporting! I wonder if there's a way to have the GitHub actions on the repo but not included as part of the "template"... I'll investigate! Although the workflow is useful for people who _do_ want to deploy to GitHub pages, so maybe it should be an option. Hmm.

In the meantime you can turn the action off by deleting `.github/workflows/deploy.yml`.

Why the build on your repo is failing is another puzzle...

**Comment by frankieroberto** [comment]
@vickytnz Ah, so it looks like there are 2 separate issues:

* the [`deploy.yml` is failing](https://github.com/vickytnz/xgov-design-history/actions/runs/9863705378/job/27237059922) because GitHub Pages isn't enabled - you have to do this within Settings first, and then the deploy script would work
* the [pages build and deployment / build](https://github.com/vickytnz/xgov-design-history/actions/runs/9863917333/job/27237725975) is I think not being triggered by any action included in the repo, but is instead the default one used if you have 'Classic' pages enabled?

I think if you were to change this setting from 'Deploy from a branch (GitHub Classic)' to 'GitHub Actions' then it might all work?

<img width="337" alt="Screenshot 2024-07-09 at 22 35 36" src="https://github.com/x-govuk/govuk-design-history-template/assets/30665/482b0335-fa9d-4fdf-9308-a84ccce3d06a">

(and yes this is all needlessly fiddly... We'll have to try and improve the documentation on this to get people through these initial hurdles!)
